language: python
python:
  - '3.7'
os: linux


install:
  - pip install -r requirements.txt
  
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE library;'
  - mysql>source library.sql

script:
  - pytest
