swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /books:
    get:
      operationId: books.read_all
      tags:
        - Books
      summary: Read the entire list of books
      description: Read the list of books
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of books to get from books
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering books
          required: false
      responses:
        200:
          description: Successfully read books list operation
          schema:
            type: array
            items:
              properties:
                author:
                  type: string
                year:
                  type: integer
                timestamp:
                  type: string